// Optional browser QA: use an installed Playwright module and Chromium.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.TEST_BASE_URL || 'http://localhost:3000';
(async () => {
  fs.mkdirSync('output/frontend-qa', {recursive:true});
  const browser = await chromium.launch({headless:true, ...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),args:['--no-sandbox']});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  page.setDefaultTimeout(12000);
  const errors=[],checks=[];
  page.on('pageerror',error=>errors.push(error.message));
  const open=async path=>{await page.goto(base+path);await page.locator('main h1').first().waitFor();};
  const checkWidth=async()=>{const result=await page.evaluate(()=>({document:document.documentElement.scrollWidth,viewport:innerWidth}));assert.ok(result.document<=result.viewport+1,JSON.stringify(result));};
  await open('/demo');await page.waitForTimeout(500);await page.screenshot({path:'output/frontend-qa/dashboard-desktop.png',fullPage:true});checks.push('Dashboard desktop');
  await page.getByRole('link',{name:/Stock & catalogue/}).click();await page.getByRole('heading',{name:'Le bon stock, au bon endroit.'}).waitFor();
  await page.getByRole('button',{name:'Nouvelle entrée',exact:true}).click();await page.getByLabel('Quantité',{exact:false}).fill('2000');await page.getByLabel('Coût unitaire',{exact:false}).fill('300000');await page.getByRole('button',{name:'Vérifier',exact:false}).click();await page.getByRole('button',{name:'Confirmer',exact:true}).click();await page.getByRole('status').filter({hasText:'Opération enregistrée'}).waitFor();
  await page.getByRole('button',{name:'Ouvrir le détail p0'}).click();await page.getByRole('heading',{name:'Apple iPhone 15',exact:true}).waitFor();assert.ok((await page.locator('.compact-metrics').innerText()).includes('2018'));checks.push('Entrée de 2000 unités sans IMEI');
  await page.getByRole('link',{name:'Caisse / Vendre',exact:true}).click();await page.getByRole('heading',{name:'Une nouvelle vente.'}).waitFor();
  await page.getByRole('button',{name:/Apple iPhone 15/}).click();await page.getByRole('button',{name:'Augmenter Apple iPhone 15'}).click();await page.getByRole('button',{name:'Augmenter Apple iPhone 15'}).click();await page.screenshot({path:'output/frontend-qa/pos-desktop.png',fullPage:true});
  await page.getByRole('button',{name:/Encaisser/}).click();await page.getByRole('button',{name:'Confirmer',exact:true}).click();await page.getByRole('heading',{name:/Reçu OP/}).waitFor();await page.emulateMedia({media:'print'});assert.equal(await page.locator('.receipt').isVisible(),true);await page.screenshot({path:'output/frontend-qa/receipt-print.png',fullPage:true});await page.emulateMedia({media:'screen'});await page.getByRole('button',{name:'Fermer',exact:true}).last().click();checks.push('Vente de 3 unités, reçu et impression');
  await page.getByRole('link',{name:/Stock & catalogue/}).click();await page.getByRole('button',{name:'Ouvrir le détail p0'}).click();await page.getByRole('heading',{name:'Apple iPhone 15',exact:true}).waitFor();assert.ok((await page.locator('.compact-metrics').innerText()).includes('2015'));checks.push('Stock après vente : 2015 unités');
  await page.getByRole('combobox',{name:'Boutique active'}).selectOption('s2');await page.getByRole('link',{name:/Stock & catalogue/}).click();await page.getByRole('heading',{name:'Le bon stock, au bon endroit.'}).waitFor();assert.equal(await page.getByRole('button',{name:'Ouvrir le détail p0'}).count(),0);assert.equal(await page.getByRole('button',{name:'Ouvrir le détail p8'}).count(),1);checks.push('Isolation des boutiques dans les listes');
  await page.getByRole('combobox',{name:'Boutique active'}).selectOption('s1');await page.getByRole('combobox',{name:'Rôle de démonstration'}).selectOption('cashier');await page.getByRole('heading',{name:'Une nouvelle vente.'}).waitFor();assert.equal(await page.getByRole('link',{name:'Comptabilité',exact:true}).count(),0);await page.getByRole('link',{name:/Stock & catalogue/}).click();await page.getByRole('heading',{name:'Le bon stock, au bon endroit.'}).waitFor();assert.equal(await page.getByRole('columnheader',{name:'Valeur du stock'}).count(),0);assert.equal(await page.getByRole('button',{name:'Nouvelle entrée',exact:true}).count(),0);checks.push('Caissier : aucun accès coûts/comptabilité/ajustement');
  await page.getByRole('combobox',{name:'Rôle de démonstration'}).selectOption('owner');await page.getByRole('link',{name:'Comptabilité',exact:true}).click();await page.getByRole('heading',{name:'Des comptes en équilibre.'}).waitFor();await page.getByRole('button',{name:'Nouvelle écriture'}).click();await page.getByLabel('Libellé de l’écriture').fill('Test QA équilibré');await page.getByLabel('Débit ligne 1').fill('10000');assert.equal(await page.getByRole('button',{name:'Enregistrer le brouillon'}).isDisabled(),true);await page.getByLabel('Crédit ligne 2').fill('10000');await page.getByRole('button',{name:'Enregistrer le brouillon'}).click();await page.getByRole('cell',{name:'Test QA équilibré',exact:true}).waitFor();checks.push('Écriture : déséquilibre bloqué puis brouillon équilibré');
  const routes=['/demo/sales','/demo/trade','/demo/buyback','/demo/purchases','/demo/suppliers','/demo/expenses','/demo/payments','/demo/cash','/demo/clients','/demo/team','/demo/audit','/demo/settings','/demo/settings/fiscal','/demo/accounting/accounts','/demo/accounting/ledger','/demo/accounting/trial-balance','/demo/accounting/statements','/demo/accounting/periods','/demo/analytics','/demo/analytics/stock','/demo/analytics/clients','/demo/analytics/cash','/demo/analytics/accounting','/demo/analytics/trade'];
  for(const path of routes){await open(path);await checkWidth();assert.equal(await page.getByText('Cette page n’a pas pu s’afficher.',{exact:true}).count(),0);}
  checks.push(`${routes.length} routes métier sans erreur`);
  await open('/demo/analytics');await page.locator('.recharts-bar-rectangle').first().waitFor();await page.locator('.recharts-bar-rectangle').first().click();await page.waitForURL('**/demo/sales?brand=**');assert.ok(!page.url().includes('undefined'));checks.push('Drill-down graphique vers les ventes');
  for(const width of [768,360]){await page.setViewportSize({width,height:900});for(const path of ['/demo','/demo/stock','/demo/pos','/demo/accounting/trial-balance']){await open(path);await checkWidth();await page.screenshot({path:`output/frontend-qa/${path.split('/').filter(Boolean).join('-')}-${width}.png`,fullPage:true});}checks.push(`Responsive ${width}px`);}
  await page.goto(base+'/');await page.getByRole('link',{name:/Explorer la démonstration/}).waitFor();checks.push('API absente : état explicite, aucun faux succès');
  await page.goto(base+'/login');await page.getByRole('heading',{name:'Heureux de vous retrouver.'}).waitFor();await page.screenshot({path:'output/frontend-qa/login-mobile.png',fullPage:true});
  const response=await page.request.post(base+'/api/v1/commands',{data:{},headers:{Origin:'https://example.invalid'}});assert.equal(response.status(),403);checks.push('Proxy : mutation externe refusée');
  const oldAuth=await page.request.post(base+'/api/auth',{data:{action:'change_password'}});assert.equal(oldAuth.status(),410);checks.push('Ancien endpoint sensible retiré');
  assert.deepEqual(errors,[]);
  fs.writeFileSync('output/frontend-qa/browser-results.json',JSON.stringify({date:new Date().toISOString(),checks,pageErrors:errors},null,2));console.log(JSON.stringify({checks,pageErrors:errors},null,2));await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
